CREATE DATABASE IF NOT EXISTS ECOMMERCE_DATA_PLATFORM;

USE DATABASE ECOMMERCE_DATA_PLATFORM;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS AUDIT;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

SHOW SCHEMAS IN DATABASE ECOMMERCE_DATA_PLATFORM;