USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS ECOMMERCE_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::670518341963:role/SnowflakeEcommerceDataPlatformRole'
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = (
        's3://ecommerce-data-platform-2026-752/'
    );

DESC INTEGRATION ECOMMERCE_S3_INTEGRATION;