USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE;

SHOW FILE FORMATS IN SCHEMA ECOMMERCE_DATA_PLATFORM.RAW;