USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA RAW;

CREATE STAGE IF NOT EXISTS ECOMMERCE_S3_STAGE
    URL = 's3://ecommerce-data-platform-2026-752/'
    STORAGE_INTEGRATION = ECOMMERCE_S3_INTEGRATION;