USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA AUDIT;

CREATE TABLE IF NOT EXISTS PIPELINE_LOAD_AUDIT (
    RUN_DATE DATE,
    DATASET_NAME VARCHAR,
    SOURCE_FILE VARCHAR,
    S3_KEY VARCHAR,
    FILE_CHECKSUM VARCHAR,
    ROW_COUNT NUMBER,
    VALIDATION_STATUS VARCHAR,
    LOAD_STATUS VARCHAR,
    RECORDS_LOADED NUMBER,
    ERROR_MESSAGE VARCHAR,
    LOAD_STARTED_AT TIMESTAMP_NTZ,
    LOAD_COMPLETED_AT TIMESTAMP_NTZ
);

SHOW TABLES IN SCHEMA ECOMMERCE_DATA_PLATFORM.AUDIT;