USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA AUDIT;

INSERT INTO PIPELINE_LOAD_AUDIT (
    RUN_DATE,
    DATASET_NAME,
    SOURCE_FILE,
    S3_KEY,
    FILE_CHECKSUM,
    ROW_COUNT,
    VALIDATION_STATUS,
    LOAD_STATUS,
    RECORDS_LOADED,
    ERROR_MESSAGE,
    LOAD_STARTED_AT,
    LOAD_COMPLETED_AT
)
SELECT
    '2026-08-31'::DATE,
    'customers',
    'customers.csv',
    'raw/customers/run_date=2026-08-31/customers.csv',
    NULL,
    500,
    'valid',
    'success',
    500,
    NULL,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP();

SELECT *
FROM PIPELINE_LOAD_AUDIT
ORDER BY LOAD_COMPLETED_AT DESC;