USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA AUDIT;

INSERT INTO PIPELINE_LOAD_AUDIT (
    RUN_DATE,
    DATASET_NAME,
    SOURCE_FILE,
    S3_KEY,
    FILE_CHECKSUM,
    ROW_COUNT,
    VALIDATION_STATUS,
    LOAD_STATUS,
    RECORDS_LOADED,
    ERROR_MESSAGE,
    LOAD_STARTED_AT,
    LOAD_COMPLETED_AT
)
SELECT
    '2026-08-31'::DATE AS RUN_DATE,
    'customers' AS DATASET_NAME,
    SPLIT_PART(FILE_NAME, '/', -1) AS SOURCE_FILE,
    FILE_NAME AS S3_KEY,
    NULL AS FILE_CHECKSUM,
    ROW_PARSED AS ROW_COUNT,
    'valid' AS VALIDATION_STATUS,
    CASE
        WHEN STATUS = 'Loaded' THEN 'success'
        ELSE LOWER(STATUS)
    END AS LOAD_STATUS,
    ROW_COUNT AS RECORDS_LOADED,
    FIRST_ERROR_MESSAGE AS ERROR_MESSAGE,
    LAST_LOAD_TIME AS LOAD_STARTED_AT,
    LAST_LOAD_TIME AS LOAD_COMPLETED_AT
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'ECOMMERCE_DATA_PLATFORM.RAW.CUSTOMERS',
        START_TIME => DATEADD('day', -1, CURRENT_TIMESTAMP())
    )
)
WHERE FILE_NAME LIKE '%raw/customers/run_date=2026-08-31/%';

SELECT *
FROM PIPELINE_LOAD_AUDIT
ORDER BY LOAD_COMPLETED_AT DESC;