USE DATABASE ECOMMERCE_DATA_PLATFORM;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    REGION VARCHAR,
    SEGMENT VARCHAR,
    STATUS VARCHAR,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2),
    COST NUMBER(10,2),
    ACTIVE_FLAG BOOLEAN,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_TS TIMESTAMP_NTZ,
    STATUS VARCHAR,
    CHANNEL VARCHAR,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR,
    ORDER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID VARCHAR,
    ORDER_ID VARCHAR,
    AMOUNT NUMBER(10,2),
    PAYMENT_METHOD VARCHAR,
    PAYMENT_STATUS VARCHAR,
    PAYMENT_TS TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SHIPMENTS (
    SHIPMENT_ID VARCHAR,
    ORDER_ID VARCHAR,
    SHIPPED_AT TIMESTAMP_NTZ,
    DELIVERED_AT TIMESTAMP_NTZ,
    CARRIER VARCHAR,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETURNS (
    RETURN_ID VARCHAR,
    ORDER_ID VARCHAR,
    RETURNED_AT TIMESTAMP_NTZ,
    RETURN_AMOUNT NUMBER(10,2),
    RETURN_REASON VARCHAR,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS INVENTORY (
    PRODUCT_ID VARCHAR,
    SNAPSHOT_TS TIMESTAMP_NTZ,
    QUANTITY_ON_HAND NUMBER,
    REORDER_POINT NUMBER,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS WEB_EVENTS (
    EVENT_ID VARCHAR,
    SESSION_ID VARCHAR,
    EVENT_TYPE VARCHAR,
    PRODUCT_ID VARCHAR,
    TRAFFIC_SOURCE VARCHAR,
    EVENT_TS TIMESTAMP_NTZ,
    SOURCE_FILE VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SHOW TABLES IN SCHEMA ECOMMERCE_DATA_PLATFORM.RAW;